# Generated by Django 5.2.7 on 2025-12-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('pmcid', models.IntegerField(primary_key=True, serialize=False)),
                ('pmid', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('authors', models.CharField(max_length=100)),
                ('first_author', models.TextField(max_length=100)),
                ('journal', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('date', models.DateField(default='2025-01-01')),
                ('doi', models.TextField(max_length=100)),
                ('organism', models.TextField()),
                ('url', models.URLField()),
                ('type', models.TextField(max_length=100)),
                ('ds', models.CharField(blank=True, max_length=100, null=True)),
                ('pdf_path', models.TextField()),
                ('axis', models.CharField(max_length=100)),
                ('abstract', models.TextField(max_length=100)),
            ],
            options={
                'db_table': 'article',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('affiliation', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(blank=True)),
            ],
        ),
    ]
